version: "3.3"

# replace /path/to/dir/ to point to config.json

# The RabbitMQ and CouchDB services can take some time to startup.
# During this time most of the pyspider services will exit and restart.
# Once RabbitMQ and CouchDB are fully up and running everything should run as normal.

services:
  rabbitmq:
    image: rabbitmq:alpine
    container_name: rabbitmq
    networks:
      - pyspider
    command: rabbitmq-server
  mysql:
    image: mariadb
    container_name: mysql
    volumes:
      - ./data:/var/lib/mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_USER=root
    networks:
      - pyspider
  phantomjs:
    image: pyspider:latest
    container_name: phantomjs
    networks:
      - pyspider
    volumes:
      - ./config.json:/opt/pyspider/config.json
      - ./projects:/opt/pyspider/projects
    command: -c config.json phantomjs
    restart: unless-stopped
  result:
    image: pyspider:latest
    container_name: result
    networks:
      - pyspider
    volumes:
      - ./config.json:/opt/pyspider/config.json
      - ./projects:/opt/pyspider/projects
    command: -c config.json result_worker
    restart: unless-stopped # Sometimes we'll get a connection refused error because couchdb has yet to fully start
    links:
      - mysql:mysql
  processor:
    container_name: processor
    image: pyspider:latest
    networks:
      - pyspider
    volumes:
      - ./config.json:/opt/pyspider/config.json
      - ./projects:/opt/pyspider/projects
    command: -c config.json processor
    restart: unless-stopped
    links:
      - mysql:mysql
  fetcher:
    image: pyspider:latest
    container_name: fetcher
    networks:
      - pyspider
    volumes:
      - ./config.json:/opt/pyspider/config.json
      - ./projects:/opt/pyspider/projects
    command : -c config.json fetcher
    restart: unless-stopped
  scheduler:
    image: pyspider:latest
    container_name: scheduler
    networks:
      - pyspider
    volumes:
      - ./config.json:/opt/pyspider/config.json
      - ./projects:/opt/pyspider/projects
    command: -c config.json scheduler
    restart: unless-stopped
    links:
      - mysql:mysql
  webui:
    image: pyspider:latest
    container_name: webui
    ports:
      - "8888:5000"
    networks:
      - pyspider
    volumes:
      - ./config.json:/opt/pyspider/config.json
      - ./projects:/opt/pyspider/projects
    command: -c config.json webui
    restart: unless-stopped
    links:
      - mysql:mysql

networks:
  pyspider:
    external:
      name: pyspider
  default:
    driver: bridge
